buzzer.c File Reference
#include <main.h>
#include <tim.h>
#include `buzzer.h`
#include <abstraction/gpio.h>
#include <feedback/still_alive.h>
#include `note.h`
Macros
#define NOTE_TIMER_DEV htim14
#define RYTM_TIMER_DEV htim16
#define NOTE_TIMER NOTE_TIMER_DEV.Instance
#define RYTM_TIMER RYTM_TIMER_DEV.Instance
#define BUZZER_PIN GPIO_PIN_3
#define BUZZER_PORT GPIOC
#define TIMER_FREQ 200e6
#define NOTE_PRESC 10
#define RYTM_PRESC 20000
#define TIMER_TRIM -1e6
#define COMPUTE_NOTE(note) ((((TIMER_FREQ)+(TIMER_TRIM))*10)/(NOTE_PRESC)/(note))/2
#define RYTM_MS(ms) (ms)*(((TIMER_FREQ)+(TIMER_TRIM))/(RYTM_PRESC))/(1000)
#define COMPUTE_RYTM(time) RYTM_MS((time)*100)
Functions
void buzzer_note_interrupt (void)
void buzzer_rytm_interrupt (void)
void buzzer_enable (void)
void buzzer_disable (void)
void buzzer_init (void)
Variables
static uint16_t melody_state = 0
static uint8_t state = 0
static uint8_t melody_active = 1
Macro Definition Documentation
BUZZER_PIN
#define BUZZER_PIN GPIO_PIN_3
BUZZER_PORT
#define BUZZER_PORT GPIOC
COMPUTE_NOTE
#define COMPUTE_NOTE(note) ((((TIMER_FREQ)+(TIMER_TRIM))*10)/(NOTE_PRESC)/(note))/2
COMPUTE_RYTM
#define COMPUTE_RYTM(time) RYTM_MS((time)*100)
NOTE_PRESC
#define NOTE_PRESC 10
NOTE_TIMER
#define NOTE_TIMER NOTE_TIMER_DEV.Instance
NOTE_TIMER_DEV
#define NOTE_TIMER_DEV htim14
RYTM_MS
#define RYTM_MS(ms) (ms)*(((TIMER_FREQ)+(TIMER_TRIM))/(RYTM_PRESC))/(1000)
RYTM_PRESC
#define RYTM_PRESC 20000
RYTM_TIMER
#define RYTM_TIMER RYTM_TIMER_DEV.Instance
RYTM_TIMER_DEV
#define RYTM_TIMER_DEV htim16
TIMER_FREQ
#define TIMER_FREQ 200e6
TIMER_TRIM
#define TIMER_TRIM -1e6
Function Documentation
buzzer_disable()
void buzzer_disable (void)
References NOTE_TIMER_DEV, and RYTM_TIMER_DEV.
buzzer_enable()
void buzzer_enable (void)
References NOTE_TIMER_DEV, and RYTM_TIMER_DEV.
buzzer_init()
void buzzer_init (void)
References A4, BUZZER_PIN, BUZZER_PORT, COMPUTE_NOTE, COMPUTE_RYTM, melody_active, NOTE_TIMER, and RYTM_TIMER.
Referenced by threads_init().
buzzer_note_interrupt()
void buzzer_note_interrupt (void)
References BUZZER_PIN, BUZZER_PORT, gpio_clr(), gpio_set(), melody_active, and state.
buzzer_rytm_interrupt()
void buzzer_rytm_interrupt (void)
References COMPUTE_NOTE, gpio_clr(), gpio_set(), melody_active, melody_state, NOTE_TIMER, still_alive, and still_alive_len.
Variable Documentation
melody_active
uint8_t melody_active = 1 [static]
Referenced by buzzer_init(), buzzer_note_interrupt(), and buzzer_rytm_interrupt().
melody_state
uint16_t melody_state = 0 [static]
Referenced by buzzer_rytm_interrupt().
state
uint8_t state = 0 [static]
Referenced by buzzer_note_interrupt().