buzzer.h File Reference
#include <stdint.h>
Functions
void buzzer_note_interrupt (void)
void buzzer_rytm_interrupt (void)
void buzzer_enable (void)
void buzzer_disable (void)
void buzzer_init (void)
Function Documentation
buzzer_disable()
void buzzer_disable (void)
References NOTE_TIMER_DEV, and RYTM_TIMER_DEV.
buzzer_enable()
void buzzer_enable (void)
References NOTE_TIMER_DEV, and RYTM_TIMER_DEV.
buzzer_init()
void buzzer_init (void)
References A4, BUZZER_PIN, BUZZER_PORT, COMPUTE_NOTE, COMPUTE_RYTM, melody_active, NOTE_TIMER, and RYTM_TIMER.
Referenced by threads_init().
buzzer_note_interrupt()
void buzzer_note_interrupt (void)
References BUZZER_PIN, BUZZER_PORT, gpio_clr(), gpio_set(), melody_active, and state.
buzzer_rytm_interrupt()
void buzzer_rytm_interrupt (void)
References COMPUTE_NOTE, gpio_clr(), gpio_set(), melody_active, melody_state, NOTE_TIMER, still_alive, and still_alive_len.