control.c File Reference
#include <main.h>
#include <gpio.h>
#include <usart.h>
#include <cmsis_os.h>
#include <driver/serial.h>
#include <device/device.h>
#include <device/i2c_sensor.h>
#include <device/hostproc.h>
#include <control.h>
#include <feedback/led.h>
#include <feedback/buzzer.h>
Data Structures
struct control
Macros
#define CONTROL_HEART_BEAT 200
Typedefs
typedef enum control_state control_state_t
State of the control FSM.
typedef struct control control_t
Enumerations
enum control_state {
CONTROL_IDLE
, CONTROL_CALIBRATION
, CONTROL_ARMED
, CONTROL_POWERED
,
CONTROL_SUPERSONIC
, CONTROL_COAST
, CONTROL_APOGEE
, CONTROL_DROGUE
,
CONTROL_EVENT
, CONTROL_MAIN
, CONTROL_TOUCHDOWN
, CONTROL_BALLISTIC
,
CONTROL_ERROR
, CONTROL_ABORT
 }
State of the control FSM.
Functions
void control_idle_start (void)
Idle state entry.
void control_idle_run (void)
Idle state runtime.
void control_calibration_start (void)
Calibration state entry.
void control_calibration_run (void)
Calibration state runtime.
void control_armed_start (void)
Armed state entry.
void control_armed_run (void)
Armed state runtime.
void control_powered_start (void)
Powered state entry.
void control_powered_run (void)
Powered state runtime.
void control_supersonic_start (void)
Supersonic state entry.
void control_supersonic_run (void)
Supersonic state runtime.
void control_coast_start (void)
Coast state entry.
void control_coast_run (void)
Coast state runtime.
void control_apogee_start (void)
Apogee state entry.
void control_apogee_run (void)
Apogee state runtime.
void control_drogue_start (void)
Drogue state entry.
void control_drogue_run (void)
Drogue state runtime.
void control_event_start (void)
Event state entry.
void control_event_run (void)
Event state runtime.
void control_main_start (void)
Main state entry.
void control_main_run (void)
Main state runtime.
void control_touchdown_start (void)
Touchdown state entry.
void control_touchdown_run (void)
Touchdown state runtime.
void control_ballistic_start (void)
Ballistic state entry.
void control_ballistic_run (void)
Ballistic state runtime.
void control_error_start (void)
Error state entry.
void control_error_run (void)
Error state runtime.
void control_abort_start (void)
Abort state entry.
void control_abort_run (void)
Abort state runtime.
void control_thread (__attribute__((unused)) void *arg)
Control thread entry point.
Variables
control_t control
Macro Definition Documentation
CONTROL_HEART_BEAT
#define CONTROL_HEART_BEAT 200
Typedef Documentation
control_state_t
typedef enum control_state control_state_t
State of the control FSM.
control_t
typedef struct control control_t
Enumeration Type Documentation
control_state
enum control_state
State of the control FSM.
Enumerator
CONTROL_IDLE Wait for arming or calibration
CONTROL_CALIBRATION Calibrate sensors and actuators
CONTROL_ARMED Armed, wait for liftoff
CONTROL_POWERED Powered ascent
CONTROL_SUPERSONIC Supersonic flight
CONTROL_COAST Subsonic, coast flight
CONTROL_APOGEE Apogee reached, trigger first event
CONTROL_DROGUE Drogue chute descent, wait for second event
CONTROL_EVENT Low alt reached, trigger second event
CONTROL_MAIN Main chute descent, wait for touchdown
CONTROL_TOUCHDOWN Touchdown detected, end of the flight
CONTROL_BALLISTIC Ballistic flight detected
CONTROL_ERROR Auto triggered error
CONTROL_ABORT User triggered error
Function Documentation
control_abort_run()
void control_abort_run (void)
Abort state runtime.
control_abort_start()
void control_abort_start (void)
Abort state entry.
References CONTROL_ABORT, and control::state.
control_apogee_run()
void control_apogee_run (void)
Apogee state runtime.
control_apogee_start()
void control_apogee_start (void)
Apogee state entry.
References CONTROL_APOGEE, and control::state.
control_armed_run()
void control_armed_run (void)
Armed state runtime.
control_armed_start()
void control_armed_start (void)
Armed state entry.
References CONTROL_ARMED, and control::state.
control_ballistic_run()
void control_ballistic_run (void)
Ballistic state runtime.
control_ballistic_start()
void control_ballistic_start (void)
Ballistic state entry.
References CONTROL_BALLISTIC, and control::state.
control_calibration_run()
void control_calibration_run (void)
Calibration state runtime.
control_calibration_start()
void control_calibration_start (void)
Calibration state entry.
References CONTROL_CALIBRATION, and control::state.
control_coast_run()
void control_coast_run (void)
Coast state runtime.
control_coast_start()
void control_coast_start (void)
Coast state entry.
References CONTROL_COAST, and control::state.
control_drogue_run()
void control_drogue_run (void)
Drogue state runtime.
control_drogue_start()
void control_drogue_start (void)
Drogue state entry.
References CONTROL_DROGUE, and control::state.
control_error_run()
void control_error_run (void)
Error state runtime.
control_error_start()
void control_error_start (void)
Error state entry.
References CONTROL_ERROR, and control::state.
control_event_run()
void control_event_run (void)
Event state runtime.
control_event_start()
void control_event_start (void)
Event state entry.
References CONTROL_EVENT, and control::state.
control_idle_run()
void control_idle_run (void)
Idle state runtime.
control_idle_start()
void control_idle_start (void)
Idle state entry.
References CONTROL_IDLE, and control::state.
control_main_run()
void control_main_run (void)
Main state runtime.
control_main_start()
void control_main_start (void)
Main state entry.
References CONTROL_MAIN, and control::state.
control_powered_run()
void control_powered_run (void)
Powered state runtime.
control_powered_start()
void control_powered_start (void)
Powered state entry.
References CONTROL_POWERED, and control::state.
control_supersonic_run()
void control_supersonic_run (void)
Supersonic state runtime.
control_supersonic_start()
void control_supersonic_start (void)
Supersonic state entry.
References CONTROL_SUPERSONIC, and control::state.
control_thread()
void control_thread (__attribute__((unused)) void * arg)
Control thread entry point.
This thread holds the main state machine of the WildhornAV software. It will be the main decision point for actions to be taken with respect to real world events.
Parameters
arg freertos thread entry point context (unused)
References CONTROL_HEART_BEAT, device_interface_send(), hostproc_get_interface(), hostproc_interface, and led_rgb_set_rgb().
Referenced by threads_init().
control_touchdown_run()
void control_touchdown_run (void)
Touchdown state runtime.
control_touchdown_start()
void control_touchdown_start (void)
Touchdown state entry.
References CONTROL_TOUCHDOWN, and control::state.
Variable Documentation
control
control_t control