debug.c File Reference
#include <protocol/msv2.h>
#include <feedback/debug.h>
#include <driver/serial.h>
Data Structures
struct debug_interface_context
struct debug_context
Typedefs
typedef struct debug_interface_context debug_interface_context_t
typedef struct debug_context debug_context_t
Functions
util_error_t debug_init (void)
Variables
debug_context_t debug_context
serial_interface_context_t feedback_interface_context
debug_interface_context_t debug_interface_context
Typedef Documentation
debug_context_t
typedef struct debug_context debug_context_t
debug_interface_context_t
typedef struct debug_interface_context debug_interface_context_t
Function Documentation
debug_init()
util_error_t debug_init (void)
References device_interface_create(), feedback_interface, feedback_interface_context, debug_interface_context::msv2, msv2_init(), serial_deamon, serial_get_feedback_interface(), serial_recv(), serial_send(), serial_setup_reception(), and SERIAL_TRANSFER_IT.
Variable Documentation
debug_context
debug_context_t debug_context
debug_interface_context
debug_interface_context_t debug_interface_context
feedback_interface_context
serial_interface_context_t feedback_interface_context
Referenced by debug_init().