device.c File Reference
#include <cmsis_os.h>
#include <util.h>
#include `device.h`
Macros
#define LEN_32 4
#define LEN_16 2
#define LEN_8 1
Functions
void device_deamon_thread (void *arg)
Generic device deamon thread.
util_error_t device_create (device_t *dev, void *context, device_interface_t *interface, util_error_t(*read_reg)(void *, device_interface_t *, uint32_t, uint8_t *, uint32_t), util_error_t(*write_reg)(void *, device_interface_t *, uint32_t, uint8_t *, uint32_t))
Initialize a device instance.
util_error_t device_interface_create (device_interface_t *interface, void *context, device_deamon_t *deamon, util_error_t(*send)(void *, uint8_t *, uint32_t), util_error_t(*recv)(void *, uint8_t *, uint32_t *), util_error_t(*handle_data)(void *, void *))
Initialize a device interface instance.
util_error_t device_deamon_create (device_deamon_t *deamon, const char *name, uint32_t prio, void *context, util_error_t(*data_rdy)(void *))
Initializea device deamon instance.
util_error_t device_interface_send (device_interface_t *interface, uint8_t *data, uint32_t len)
Send raw data through the interface specific send function.
util_error_t device_interface_recv (device_interface_t *interface, uint8_t *data, uint32_t *len)
Receive raw data through the interface specific recv function.
util_error_t device_write_i32 (device_t *dev, uint32_t addr, int32_t data)
Write an int32_t to a device register.
util_error_t device_write_u32 (device_t *dev, uint32_t addr, uint32_t data)
Write an uint32_t to a device register.
util_error_t device_write_i16 (device_t *dev, uint32_t addr, int16_t data)
Write an int16_t to a device register.
util_error_t device_write_u16 (device_t *dev, uint32_t addr, uint16_t data)
Write an uint16_t to a device register.
util_error_t device_write_i8 (device_t *dev, uint32_t addr, int8_t data)
Write an int8_t to a device register.
util_error_t device_write_u8 (device_t *dev, uint32_t addr, uint8_t data)
Write an uint8_t to a device register.
util_error_t device_read_i32 (device_t *dev, uint32_t addr, int32_t *data)
Read from an int32_t device register.
util_error_t device_read_u32 (device_t *dev, uint32_t addr, uint32_t *data)
Read from an uint32_t device register.
util_error_t device_read_i16 (device_t *dev, uint32_t addr, int16_t *data)
Read from an int16_t device register.
util_error_t device_read_u16 (device_t *dev, uint32_t addr, uint16_t *data)
Read from an uint16_t device register.
util_error_t device_read_i8 (device_t *dev, uint32_t addr, int8_t *data)
Read from an int8_t device register.
util_error_t device_read_u8 (device_t *dev, uint32_t addr, uint8_t *data)
Read from an uint8_t device register.
Macro Definition Documentation
LEN_16
#define LEN_16 2
LEN_32
#define LEN_32 4
LEN_8
#define LEN_8 1
Function Documentation
device_create()
util_error_t device_create (device_t * dev, void * context, device_interface_t * interface, util_error_t(*)(void *, device_interface_t *, uint32_t, uint8_t *, uint32_t) read_reg, util_error_t(*)(void *, device_interface_t *, uint32_t, uint8_t *, uint32_t) write_reg)
Initialize a device instance.
Parameters
dev Pointer to the device_t structure describing this device.
context Generic pointer to a device context.
interface Pointer to the device_interface_t associated with this device.
read_reg Pointer to a read register function for this device.
write_reg Pointer to a write register function for this device.
References device::context, ER_SUCCESS, device::id, device::interface, read_reg(), device::read_reg, write_reg(), and device::write_reg.
Referenced by i2c_sensor_init().
device_deamon_create()
util_error_t device_deamon_create (device_deamon_t * deamon, const char * name, uint32_t prio, void * context, util_error_t(*)(void *) data_rdy)
Initializea device deamon instance.
Parameters
deamon
name
prio
context
data_rdy
References device_deamon::buffer, device_deamon::context, device_deamon::data_rdy, DEAMON_STACK_SIZE, device_deamon_thread(), ER_RESSOURCE_ERROR, ER_SUCCESS, device_deamon::handle, device_deamon::id, device_deamon::interfaces_count, and device_deamon::stack.
Referenced by serial_init().
device_deamon_thread()
void device_deamon_thread (void * arg)
Generic device deamon thread.
This thread will call the handle data function for an interface, whenever data is ready for a group of interfaces belonging to the same deamon.
Parameters
arg FreeRTOS entry point context, used to pass the deamon context to the thread.
References device_interface::context, device_deamon::context, device_deamon::data_rdy, ER_SUCCESS, device_interface::handle_data, and device_deamon::interfaces_count.
Referenced by device_deamon_create().
device_interface_create()
util_error_t device_interface_create (device_interface_t * interface, void * context, device_deamon_t * deamon, util_error_t(*)(void *, uint8_t *, uint32_t) send, util_error_t(*)(void *, uint8_t *, uint32_t *) recv, util_error_t(*)(void *, void *) handle_data)
Initialize a device interface instance.
Parameters
interface
context
deamon
send
recv
handle_data
References device_interface::context, ER_SUCCESS, device_interface::handle_data, device_interface::id, device_deamon::interfaces, device_deamon::interfaces_count, device_interface::recv, and device_interface::send.
Referenced by debug_init(), hostproc_init(), i2c_init(), and serial_feedback_init().
device_interface_recv()
util_error_t device_interface_recv (device_interface_t * interface, uint8_t * data, uint32_t * len)
Receive raw data through the interface specific recv function.
Parameters
interface The interface through which data should be received.
data A point to the data to be received.
len A pointer to the length of the data to be received.
References device_interface::context, ER_RESSOURCE_ERROR, device_interface::recv, and device_interface::send.
device_interface_send()
util_error_t device_interface_send (device_interface_t * interface, uint8_t * data, uint32_t len)
Send raw data through the interface specific send function.
Parameters
interface The interface through which data should be sent.
data A point to the data to be sent.
len The length of the data to be sent.
References device_interface::context, ER_RESSOURCE_ERROR, and device_interface::send.
Referenced by control_thread().
device_read_i16()
util_error_t device_read_i16 (device_t * dev, uint32_t addr, int16_t * data)
Read from an int16_t device register.
Parameters
dev A pointer to the desired device.
addr The address of the register.
data A pointer to the data to be read.
References device::context, ER_SUCCESS, device::interface, LEN_16, device::read_reg, and util_decode_i16().
device_read_i32()
util_error_t device_read_i32 (device_t * dev, uint32_t addr, int32_t * data)
Read from an int32_t device register.
Parameters
dev A pointer to the desired device.
addr The address of the register.
data A pointer to the data to be read.
References device::context, ER_SUCCESS, device::interface, LEN_32, device::read_reg, and util_decode_i32().
device_read_i8()
util_error_t device_read_i8 (device_t * dev, uint32_t addr, int8_t * data)
Read from an int8_t device register.
Parameters
dev A pointer to the desired device.
addr The address of the register.
data A pointer to the data to be read.
References device::context, ER_SUCCESS, device::interface, LEN_8, device::read_reg, and util_decode_i8().
device_read_u16()
util_error_t device_read_u16 (device_t * dev, uint32_t addr, uint16_t * data)
Read from an uint16_t device register.
Parameters
dev A pointer to the desired device.
addr The address of the register.
data A pointer to the data to be read.
References device::context, ER_SUCCESS, device::interface, LEN_16, device::read_reg, and util_decode_u16().
device_read_u32()
util_error_t device_read_u32 (device_t * dev, uint32_t addr, uint32_t * data)
Read from an uint32_t device register.
Parameters
dev A pointer to the desired device.
addr The address of the register.
data A pointer to the data to be read.
References device::context, ER_SUCCESS, device::interface, LEN_32, device::read_reg, and util_decode_u32().
device_read_u8()
util_error_t device_read_u8 (device_t * dev, uint32_t addr, uint8_t * data)
Read from an uint8_t device register.
Parameters
dev A pointer to the desired device.
addr The address of the register.
data A pointer to the data to be read.
References device::context, ER_SUCCESS, device::interface, LEN_8, device::read_reg, and util_decode_u8().
device_write_i16()
util_error_t device_write_i16 (device_t * dev, uint32_t addr, int16_t data)
Write an int16_t to a device register.
Parameters
dev A pointer to the desired device.
addr The address of the register.
data The data to be written.
References device::context, ER_SUCCESS, device::interface, LEN_16, util_encode_i16(), and device::write_reg.
device_write_i32()
util_error_t device_write_i32 (device_t * dev, uint32_t addr, int32_t data)
Write an int32_t to a device register.
Parameters
dev A pointer to the desired device.
addr The address of the register.
data The data to be written.
References device::context, ER_SUCCESS, device::interface, LEN_32, util_encode_i32(), and device::write_reg.
device_write_i8()
util_error_t device_write_i8 (device_t * dev, uint32_t addr, int8_t data)
Write an int8_t to a device register.
Parameters
dev A pointer to the desired device.
addr The address of the register.
data The data to be written.
References device::context, ER_SUCCESS, device::interface, LEN_8, util_encode_i8(), and device::write_reg.
device_write_u16()
util_error_t device_write_u16 (device_t * dev, uint32_t addr, uint16_t data)
Write an uint16_t to a device register.
Parameters
dev A pointer to the desired device.
addr The address of the register.
data The data to be written.
References device::context, ER_SUCCESS, device::interface, LEN_16, util_encode_u16(), and device::write_reg.
device_write_u32()
util_error_t device_write_u32 (device_t * dev, uint32_t addr, uint32_t data)
Write an uint32_t to a device register.
Parameters
dev A pointer to the desired device.
addr The address of the register.
data The data to be written.
References device::context, ER_SUCCESS, device::interface, LEN_32, util_encode_u32(), and device::write_reg.
device_write_u8()
util_error_t device_write_u8 (device_t * dev, uint32_t addr, uint8_t data)
Write an uint8_t to a device register.
Parameters
dev A pointer to the desired device.
addr The address of the register.
data The data to be written.
References device::context, ER_SUCCESS, device::interface, LEN_8, util_encode_u8(), and device::write_reg.