gpio.h File Reference
#include <stdint.h>
#include <main.h>
Data Structures
struct gpio_config
Typedefs
typedef enum gpio_drive gpio_drive_t
typedef enum gpio_mode gpio_mode_t
typedef enum gpio_bias gpio_bias_t
typedef struct gpio_config gpio_config_t
Enumerations
enum gpio_drive { GPIO_DRIVE_PP = 0b0
, GPIO_DRIVE_OD = 0b1
 }
enum gpio_mode { GPIO_MODE_IN = 0b00
, GPIO_MODE_OUT = 0b01
, GPIO_MODE_ALT = 0b10
, GPIO_MODE_ANA = 0b11
 }
enum gpio_bias { GPIO_BIAS_NONE = 0b00
, GPIO_BIAS_HIGH = 0b01
, GPIO_BIAS_LOW = 0b10
 }
Functions
void gpio_set (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
void gpio_clr (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
uint8_t gpio_get (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
void gpio_cfg (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, gpio_config_t cfg)
Typedef Documentation
gpio_bias_t
typedef enum gpio_bias gpio_bias_t
gpio_config_t
typedef struct gpio_config gpio_config_t
gpio_drive_t
typedef enum gpio_drive gpio_drive_t
gpio_mode_t
typedef enum gpio_mode gpio_mode_t
Enumeration Type Documentation
gpio_bias
enum gpio_bias
Enumerator
GPIO_BIAS_NONE
GPIO_BIAS_HIGH
GPIO_BIAS_LOW
gpio_drive
enum gpio_drive
Enumerator
GPIO_DRIVE_PP
GPIO_DRIVE_OD
gpio_mode
enum gpio_mode
Enumerator
GPIO_MODE_IN
GPIO_MODE_OUT
GPIO_MODE_ALT
GPIO_MODE_ANA
Function Documentation
gpio_cfg()
void gpio_cfg (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin, gpio_config_t cfg)
References gpio_config::alternate, gpio_config::drive, gpio_config::mode, gpio_config::speed, and WRITE_IN_REG.
gpio_clr()
void gpio_clr (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Referenced by buzzer_note_interrupt(), and buzzer_rytm_interrupt().
gpio_get()
uint8_t gpio_get (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
gpio_set()
void gpio_set (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Referenced by buzzer_note_interrupt(), and buzzer_rytm_interrupt().