gpio.c File Reference
#include `gpio.h`
#include <util.h>
Functions
uint8_t gpio_get (GPIO_TypeDef *gpio, uint16_t pin)
void gpio_set (GPIO_TypeDef *gpio, uint16_t pin)
void gpio_clr (GPIO_TypeDef *gpio, uint16_t pin)
void gpio_cfg (GPIO_TypeDef *gpio, uint16_t pins, gpio_config_t cfg)
Function Documentation
gpio_cfg()
void gpio_cfg (GPIO_TypeDef * gpio, uint16_t pins, gpio_config_t cfg)
References gpio_config::alternate, gpio_config::drive, gpio_config::mode, gpio_config::speed, and WRITE_IN_REG.
gpio_clr()
void gpio_clr (GPIO_TypeDef * gpio, uint16_t pin)
Referenced by buzzer_note_interrupt(), and buzzer_rytm_interrupt().
gpio_get()
uint8_t gpio_get (GPIO_TypeDef * gpio, uint16_t pin)
gpio_set()
void gpio_set (GPIO_TypeDef * gpio, uint16_t pin)
Referenced by buzzer_note_interrupt(), and buzzer_rytm_interrupt().