hostproc.c File Reference
#include <main.h>
#include <cmsis_os.h>
#include <device/hostproc.h>
#include <feedback/led.h>
#include <openamp.h>
#include <util.h>
Data Structures
struct hostproc_interface_context
Typedefs
typedef struct hostproc_interface_context hostproc_interface_context_t
Functions
void host_UART0_RX (VIRT_UART_HandleTypeDef *huart)
util_error_t host_send (void *context, uint8_t *data, uint32_t len)
util_error_t host_recv (void *context, uint8_t *data, uint32_t *len)
device_interface_t * hostproc_get_interface (void)
device_t * hostproc_get_device (void)
util_error_t hostproc_init (void)
Variables
static VIRT_UART_HandleTypeDef host_UART0
static device_t hostproc_device
static device_interface_t hostproc_interface
static hostproc_interface_context_t hostproc_interface_context
Typedef Documentation
hostproc_interface_context_t
typedef struct hostproc_interface_context hostproc_interface_context_t
Function Documentation
host_recv()
util_error_t host_recv (void * context, uint8_t * data, uint32_t * len)
Referenced by hostproc_init().
host_send()
util_error_t host_send (void * context, uint8_t * data, uint32_t len)
References ER_SUCCESS, hostproc_interface_context::rx_once, and hostproc_interface_context::uart.
Referenced by hostproc_init().
host_UART0_RX()
void host_UART0_RX (VIRT_UART_HandleTypeDef * huart)
References led_rgb_set_rgb(), and hostproc_interface_context::rx_once.
Referenced by hostproc_init().
hostproc_get_device()
device_t* hostproc_get_device (void)
References hostproc_device.
hostproc_get_interface()
device_interface_t* hostproc_get_interface (void)
References hostproc_interface.
Referenced by control_thread().
hostproc_init()
util_error_t hostproc_init (void)
References device_interface_create(), ER_FAILURE, ER_SUCCESS, host_recv(), host_send(), host_UART0, host_UART0_RX(), hostproc_interface, hostproc_interface_context::rx_once, and hostproc_interface_context::uart.
Referenced by threads_init().
Variable Documentation
host_UART0
VIRT_UART_HandleTypeDef host_UART0 [static]
Referenced by hostproc_init().
hostproc_device
device_t hostproc_device [static]
Referenced by hostproc_get_device().
hostproc_interface
device_interface_t hostproc_interface [static]
Referenced by control_thread(), hostproc_get_interface(), and hostproc_init().
hostproc_interface_context
hostproc_interface_context_t hostproc_interface_context [static]