hostproc.h File Reference
#include <stdint.h>
#include <virt_uart.h>
#include <device/device.h>
Functions
device_interface_t * hostproc_get_interface (void)
device_t * hostproc_get_device (void)
util_error_t hostproc_init (void)
Function Documentation
hostproc_get_device()
device_t* hostproc_get_device (void)
References hostproc_device.
hostproc_get_interface()
device_interface_t* hostproc_get_interface (void)
References hostproc_interface.
Referenced by control_thread().
hostproc_init()
util_error_t hostproc_init (void)
References device_interface_create(), ER_FAILURE, ER_SUCCESS, host_recv(), host_send(), host_UART0, host_UART0_RX(), hostproc_interface, hostproc_interface_context::rx_once, and hostproc_interface_context::uart.
Referenced by threads_init().