i2c.c File Reference
#include <main.h>
#include <driver/i2c.h>
#include <device/device.h>
#include <util.h>
Macros
#define S1_I2C hi2c1
#define S2_I2C hi2c2
#define S3_I2C hi2c5
Functions
void i2c_spi_guard (void)
This funcion disables completely the SPI for hardware saveguard.
device_interface_t * i2c_get_sensor_interface (void)
Getter for the interface associated with the sensors.
void i2c_init (void)
Initializer for the i2c subsystem. @deails This function initializes the three i2c interfaces which are present on the hostboards.
Variables
device_interface_t sensor_interface
This is the I2C Interface associated with the sensors.
i2c_interface_context_t sensor_interface_context
Macro Definition Documentation
S1_I2C
#define S1_I2C hi2c1
S2_I2C
#define S2_I2C hi2c2
S3_I2C
#define S3_I2C hi2c5
Function Documentation
i2c_get_sensor_interface()
device_interface_t* i2c_get_sensor_interface (void)
Getter for the interface associated with the sensors.
Returns
The pointer to the sensor interface object
References sensor_interface.
Referenced by i2c_sensor_init().
i2c_init()
void i2c_init (void)
Initializer for the i2c subsystem. @deails This function initializes the three i2c interfaces which are present on the hostboards.
References device_interface_create(), ER_SUCCESS, sensor_interface, and sensor_interface_context.
Referenced by threads_init().
i2c_spi_guard()
void i2c_spi_guard (void)
This funcion disables completely the SPI for hardware saveguard.
Referenced by threads_init().
Variable Documentation
sensor_interface
device_interface_t sensor_interface
This is the I2C Interface associated with the sensors.
Referenced by i2c_get_sensor_interface(), and i2c_init().
sensor_interface_context
i2c_interface_context_t sensor_interface_context
Initial value:
= {
        .i2c = &S2_I2C
}
Referenced by i2c_init().