i2c_sensor.c File Reference
#include <main.h>
#include <device/device.h>
#include <device/i2c_sensor.h>
#include <driver/i2c.h>
#include <util.h>
Data Structures
struct i2c_sensor_context
Typedefs
typedef struct i2c_sensor_context i2c_sensor_context_t
Functions
util_error_t read_reg (void *context, device_interface_t *dev, uint32_t address, uint8_t *data, uint32_t data_len)
util_error_t write_reg (void *context, device_interface_t *dev, uint32_t address, uint8_t *data, uint32_t data_len)
device_t * i2c_get_accelerometer (void)
util_error_t i2c_sensor_init (void)
Variables
static device_t i2c_accelerometer_device
static device_t i2c_gyroscope_device
static device_t i2c_barometer_device
static i2c_sensor_context_t i2c_accelerometer_device_context
static i2c_sensor_context_t i2c_gyroscope_device_context
static i2c_sensor_context_t i2c_barometer_device_context
Typedef Documentation
i2c_sensor_context_t
typedef struct i2c_sensor_context i2c_sensor_context_t
Function Documentation
i2c_get_accelerometer()
device_t* i2c_get_accelerometer (void)
References i2c_accelerometer_device.
i2c_sensor_init()
util_error_t i2c_sensor_init (void)
References device_create(), ER_SUCCESS, i2c_accelerometer_device, i2c_accelerometer_device_context, i2c_get_sensor_interface(), read_reg(), and write_reg().
read_reg()
util_error_t read_reg (void * context, device_interface_t * dev, uint32_t address, uint8_t * data, uint32_t data_len)
References device_interface::context, ER_SUCCESS, and i2c_interface_context::i2c.
Referenced by device_create(), and i2c_sensor_init().
write_reg()
util_error_t write_reg (void * context, device_interface_t * dev, uint32_t address, uint8_t * data, uint32_t data_len)
References device_interface::context, ER_SUCCESS, and i2c_interface_context::i2c.
Referenced by device_create(), and i2c_sensor_init().
Variable Documentation
i2c_accelerometer_device
device_t i2c_accelerometer_device [static]
Referenced by i2c_get_accelerometer(), and i2c_sensor_init().
i2c_accelerometer_device_context
i2c_sensor_context_t i2c_accelerometer_device_context [static]
Initial value:
= {
        .device_address = 0x68
}
Referenced by i2c_sensor_init().
i2c_barometer_device
device_t i2c_barometer_device [static]
i2c_barometer_device_context
i2c_sensor_context_t i2c_barometer_device_context [static]
Initial value:
= {
        .device_address = 0x18
}
i2c_gyroscope_device
device_t i2c_gyroscope_device [static]
i2c_gyroscope_device_context
i2c_sensor_context_t i2c_gyroscope_device_context [static]
Initial value:
= {
        .device_address = 0x68
}