i2c_sensor.h File Reference
#include <stdint.h>
Functions
util_error_t i2c_sensor_init (void)
Function Documentation
i2c_sensor_init()
util_error_t i2c_sensor_init (void)
References device_create(), ER_SUCCESS, i2c_accelerometer_device, i2c_accelerometer_device_context, i2c_get_sensor_interface(), read_reg(), and write_reg().