i2c.h File Reference
#include <stdint.h>
#include <device/device.h>
Data Structures
struct i2c_interface_context
I2C interface context structure.
Typedefs
typedef struct i2c_interface_context i2c_interface_context_t
I2C interface context structure.
Functions
void i2c_init (void)
Initializer for the i2c subsystem. @deails This function initializes the three i2c interfaces which are present on the hostboards.
void i2c_spi_guard (void)
This funcion disables completely the SPI for hardware saveguard.
device_interface_t * i2c_get_sensor_interface (void)
Getter for the interface associated with the sensors.
Typedef Documentation
i2c_interface_context_t
typedef struct i2c_interface_context i2c_interface_context_t
I2C interface context structure.
this only contains the HAL I2C handle pointer.
Function Documentation
i2c_get_sensor_interface()
device_interface_t* i2c_get_sensor_interface (void)
Getter for the interface associated with the sensors.
Returns
The pointer to the sensor interface object
References sensor_interface.
Referenced by i2c_sensor_init().
i2c_init()
void i2c_init (void)
Initializer for the i2c subsystem. @deails This function initializes the three i2c interfaces which are present on the hostboards.
References device_interface_create(), ER_SUCCESS, sensor_interface, and sensor_interface_context.
Referenced by threads_init().
i2c_spi_guard()
void i2c_spi_guard (void)
This funcion disables completely the SPI for hardware saveguard.
Referenced by threads_init().