led.h File Reference
#include <stdint.h>
Data Structures
struct led_color
Macros
#define LED_RED 0xff, 0x00, 0x00
#define LED_GREEN 0x00, 0xff, 0x00
#define LED_BLUE 0x00, 0x00, 0xff
#define LED_ORANGE 0x7f, 0x0f, 0x07
#define LED_YELLOW 0xff, 0x1f, 0x07
#define LED_TEAL 0x00, 0x7f, 0x7f
#define LED_PINK 0x7f, 0x00, 0x7f
#define LED_LILA 0xff, 0x03, 0x4f
#define LED_BLACK 0x00, 0x00, 0x00
#define LED_WHITE 0xff, 0xff, 0xff
Typedefs
typedef struct led_color led_color_t
Functions
void led_rgb_init (void)
Initialize the RGB LED.
void led_rgb_set_color (led_color_t color)
Set RBG LED color using color structure.
void led_rgb_set_rgb (uint8_t r, uint8_t g, uint8_t b)
Set RBG LED color using r, g, b values.
void led_feedback_init (void)
Initialize the feedback module.
void led_rgb_thread (void *arg)
Variables
static const led_color_t led_red
static const led_color_t led_green
static const led_color_t led_blue
static const led_color_t led_black
Macro Definition Documentation
LED_BLACK
#define LED_BLACK 0x00, 0x00, 0x00
LED_BLUE
#define LED_BLUE 0x00, 0x00, 0xff
LED_GREEN
#define LED_GREEN 0x00, 0xff, 0x00
LED_LILA
#define LED_LILA 0xff, 0x03, 0x4f
LED_ORANGE
#define LED_ORANGE 0x7f, 0x0f, 0x07
LED_PINK
#define LED_PINK 0x7f, 0x00, 0x7f
LED_RED
#define LED_RED 0xff, 0x00, 0x00
LED_TEAL
#define LED_TEAL 0x00, 0x7f, 0x7f
LED_WHITE
#define LED_WHITE 0xff, 0xff, 0xff
LED_YELLOW
#define LED_YELLOW 0xff, 0x1f, 0x07
Typedef Documentation
led_color_t
typedef struct led_color led_color_t
Function Documentation
led_feedback_init()
void led_feedback_init (void)
Initialize the feedback module.
This will initialize a board to accept a feedback board on the S3 socket.
Referenced by threads_init().
led_rgb_init()
void led_rgb_init (void)
Initialize the RGB LED.
Starts the PWM channels connected to the RGB led for user feedback.
References LED_MAX, and LED_TIM.
Referenced by led_rgb_thread().
led_rgb_set_color()
void led_rgb_set_color (led_color_t color)
Set RBG LED color using color structure.
Parameters
color Color structure, defines the color to be set.
References led_color::b, led_color::g, LED_TIM, and led_color::r.
Referenced by led_rgb_thread().
led_rgb_set_rgb()
void led_rgb_set_rgb (uint8_t r, uint8_t g, uint8_t b)
Set RBG LED color using r, g, b values.
Parameters
r Red channel value.
g Green channel value.
b Blue channel value.
References LED_TIM.
Referenced by control_thread(), host_UART0_RX(), and led_rgb_thread().
led_rgb_thread()
void led_rgb_thread (void * arg)
Variable Documentation
led_black
const led_color_t led_black [static]
Initial value:
= {
        .r = 0x00,
        .g = 0x00,
        .b = 0x00
}
led_blue
const led_color_t led_blue [static]
Initial value:
= {
        .r = 0x00,
        .g = 0x00,
        .b = 0xff
}
Referenced by led_rgb_thread().
led_green
const led_color_t led_green [static]
Initial value:
= {
        .r = 0x00,
        .g = 0xff,
        .b = 0x00
}
led_red
const led_color_t led_red [static]
Initial value:
= {
        .r = 0xff,
        .g = 0x00,
        .b = 0x00
}