led.c File Reference
#include `led.h`
#include <main.h>
#include <tim.h>
#include <cmsis_os.h>
Macros
#define LED_TIM htim3
#define LED_MAX (0xff)
Typedefs
typedef enum led_blick_state led_blink_state_t
Enumerations
enum led_blick_state { LED_ON
, LED_FAINT
, LED_OFF
 }
Functions
void led_feedback_init (void)
Initialize the feedback module.
void led_rgb_init (void)
Initialize the RGB LED.
void led_rgb_set_rgb (uint8_t r, uint8_t g, uint8_t b)
Set RBG LED color using r, g, b values.
void led_rgb_set_color (led_color_t color)
Set RBG LED color using color structure.
void led_rgb_thread (__attribute__((unused)) void *arg)
Variables
static led_blink_state_t blink_sequence []
static const int blink_sequence_len = sizeof(blink_sequence)/sizeof(led_blink_state_t)
static led_color_t color_sequence []
static const int color_sequence_len = sizeof(color_sequence)/sizeof(led_color_t)
Macro Definition Documentation
LED_MAX
#define LED_MAX (0xff)
LED_TIM
#define LED_TIM htim3
Typedef Documentation
led_blink_state_t
typedef enum led_blick_state led_blink_state_t
Enumeration Type Documentation
led_blick_state
enum led_blick_state
Enumerator
LED_ON
LED_FAINT
LED_OFF
Function Documentation
led_feedback_init()
void led_feedback_init (void)
Initialize the feedback module.
This will initialize a board to accept a feedback board on the S3 socket.
Referenced by threads_init().
led_rgb_init()
void led_rgb_init (void)
Initialize the RGB LED.
Starts the PWM channels connected to the RGB led for user feedback.
References LED_MAX, and LED_TIM.
Referenced by led_rgb_thread().
led_rgb_set_color()
void led_rgb_set_color (led_color_t color)
Set RBG LED color using color structure.
Parameters
color Color structure, defines the color to be set.
References led_color::b, led_color::g, LED_TIM, and led_color::r.
Referenced by led_rgb_thread().
led_rgb_set_rgb()
void led_rgb_set_rgb (uint8_t r, uint8_t g, uint8_t b)
Set RBG LED color using r, g, b values.
Parameters
r Red channel value.
g Green channel value.
b Blue channel value.
References LED_TIM.
Referenced by control_thread(), host_UART0_RX(), and led_rgb_thread().
led_rgb_thread()
void led_rgb_thread (__attribute__((unused)) void * arg)
References blink_sequence, blink_sequence_len, color_sequence, color_sequence_len, LED_BLACK, led_blue, LED_FAINT, LED_OFF, LED_ON, led_rgb_init(), led_rgb_set_color(), and led_rgb_set_rgb().
Referenced by threads_init().
Variable Documentation
blink_sequence
led_blink_state_t blink_sequence[] [static]
Initial value:
= {
        LED_ON,
        LED_FAINT,
        LED_ON,
        LED_FAINT,
        LED_ON,
        LED_OFF
}
Referenced by led_rgb_thread().
blink_sequence_len
const int blink_sequence_len = sizeof(blink_sequence)/sizeof(led_blink_state_t) [static]
Referenced by led_rgb_thread().
color_sequence
led_color_t color_sequence[] [static]
Initial value:
= {
        led_green,
        led_red,
        led_blue,
        led_red,
}
Referenced by led_rgb_thread().
color_sequence_len
const int color_sequence_len = sizeof(color_sequence)/sizeof(led_color_t) [static]
Referenced by led_rgb_thread().