msv2.h File Reference
#include <util.h>
#include <stdint.h>
Data Structures
struct MSV2_RX_DATA
struct MSV2_TX_DATA
struct MSV2_INST
Macros
#define MSV2_MAX_FRAME_LEN (1024)
#define MSV2_MAX_DATA_LEN (512)
Typedefs
typedef enum MSV2_ERROR MSV2_ERROR_t
Msv2 packet creator return codes.
typedef enum MSV2_DECODE_STATE MSV2_DECODE_STATE_t
Msv2 packet decoded state.
typedef struct MSV2_RX_DATA MSV2_RX_DATA_t
typedef struct MSV2_TX_DATA MSV2_TX_DATA_t
typedef struct MSV2_INST MSV2_INST_t
Enumerations
enum MSV2_ERROR { MSV2_SUCCESS = 0
, MSV2_PROGRESS
, MSV2_WRONG_CRC
, MSV2_ERROR
 }
Msv2 packet creator return codes.
enum MSV2_DECODE_STATE {
WAITING_DLE
, WAITING_STX
, WAITING_OPCODE
, WAITING_LEN
,
WAITING_DATA
, WAITING_CRC1
, WAITING_CRC2
 }
Msv2 packet decoded state.
Functions
MSV2_ERROR_t msv2_decode_fragment (MSV2_INST_t *msv2, uint8_t d)
Decode an msv2 fragment (one byte at a time)
void msv2_init (MSV2_INST_t *msv2)
Initialize a msv2 packet creator instance.
uint16_t msv2_create_frame (MSV2_INST_t *msv2, uint8_t opcode, uint8_t data_len, uint8_t *data)
Generate an msv2 packet.
uint8_t * msv2_rx_data (MSV2_INST_t *msv2)
Getter for the pointer to the rx data array contained in the msv2 packet creator.
uint8_t * msv2_tx_data (MSV2_INST_t *msv2)
Getter for the pointer to the tx data array contained in the msv2 packet creator.
Macro Definition Documentation
MSV2_MAX_DATA_LEN
#define MSV2_MAX_DATA_LEN (512)
MSV2_MAX_FRAME_LEN
#define MSV2_MAX_FRAME_LEN (1024)
Typedef Documentation
MSV2_DECODE_STATE_t
typedef enum MSV2_DECODE_STATE MSV2_DECODE_STATE_t
Msv2 packet decoded state.
MSV2_ERROR_t
typedef enum MSV2_ERROR MSV2_ERROR_t
Msv2 packet creator return codes.
MSV2_INST_t
typedef struct MSV2_INST MSV2_INST_t
MSV2_RX_DATA_t
typedef struct MSV2_RX_DATA MSV2_RX_DATA_t
MSV2_TX_DATA_t
typedef struct MSV2_TX_DATA MSV2_TX_DATA_t
Enumeration Type Documentation
MSV2_DECODE_STATE
enum MSV2_DECODE_STATE
Msv2 packet decoded state.
Enumerator
WAITING_DLE Waiting for data Link Escape
WAITING_STX Waiting for Start of Text
WAITING_OPCODE Waiting for Opcode
WAITING_LEN Waiting for Packet Length
WAITING_DATA Waiting for Data
WAITING_CRC1 Waiting for CRC Byte 1
WAITING_CRC2 Waiting for CRC Byte 2
MSV2_ERROR
enum MSV2_ERROR
Msv2 packet creator return codes.
Enumerator
MSV2_SUCCESS Packet sucessfully decoded/encoded
MSV2_PROGRESS Packed decoding in progress
MSV2_WRONG_CRC Packet decoding error due to wrong crc
MSV2_ERROR generic error
Function Documentation
msv2_create_frame()
uint16_t msv2_create_frame (MSV2_INST_t * msv2, uint8_t opcode, uint8_t data_len, uint8_t * data)
Generate an msv2 packet.
Parameters
msv2 Pointer to the msv2 packet creator instance.
opcode Opcode to be placed in the packet header.
data_len Length of the packet data payload.
data Data to be placed in the packet payload.
References calc_field_CRC(), MSV2_TX_DATA::crc_data, MSV2_TX_DATA::data, MSV2_TX_DATA::data_len, DLE, MSV2_TX_DATA::opcode, STX, and MSV2_INST::tx.
msv2_decode_fragment()
MSV2_ERROR_t msv2_decode_fragment (MSV2_INST_t * msv2, uint8_t d)
Decode an msv2 fragment (one byte at a time)
Parameters
msv2 Pointer to the msv2 packet creator instance.
d Fragment to be decoded.
Note
This function is to be called upon reception of a byte.
References calc_field_CRC(), MSV2_RX_DATA::counter, MSV2_RX_DATA::crc, MSV2_RX_DATA::crc_data, MSV2_RX_DATA::data, MSV2_RX_DATA::data_len, DLE, MSV2_RX_DATA::escape, MSV2_RX_DATA::length, MSV2_PROGRESS, MSV2_SUCCESS, MSV2_WRONG_CRC, MSV2_RX_DATA::opcode, MSV2_INST::rx, MSV2_RX_DATA::state, STX, WAITING_CRC1, WAITING_CRC2, WAITING_DATA, WAITING_DLE, WAITING_LEN, WAITING_OPCODE, and WAITING_STX.
msv2_init()
void msv2_init (MSV2_INST_t * msv2)
Initialize a msv2 packet creator instance.
Parameters
msv2 Pointer to the msv2 instance to be initialized.
References MSV2_INST::id.
Referenced by debug_init().
msv2_rx_data()
uint8_t* msv2_rx_data (MSV2_INST_t * msv2)
Getter for the pointer to the rx data array contained in the msv2 packet creator.
Parameters
msv2 Pointer to the msv2 packet creator instance.
References MSV2_RX_DATA::data, and MSV2_INST::rx.
msv2_tx_data()
uint8_t* msv2_tx_data (MSV2_INST_t * msv2)
Getter for the pointer to the tx data array contained in the msv2 packet creator.
Parameters
msv2 Pointer to the msv2 packet creator instance.
References MSV2_TX_DATA::data, and MSV2_INST::tx.