msv2.c File Reference
#include `msv2.h`
Macros
#define DLE (0x90)
#define STX (0x02)
Functions
static uint16_t calc_field_CRC (uint16_t *p_data_array, uint16_t length)
Compute the CRC for a data packet.
void msv2_init (MSV2_INST_t *msv2)
Initialize a msv2 packet creator instance.
uint16_t msv2_create_frame (MSV2_INST_t *msv2, uint8_t opcode, uint8_t data_len, uint8_t *data)
Generate an msv2 packet.
MSV2_ERROR_t msv2_decode_fragment (MSV2_INST_t *msv2, uint8_t d)
Decode an msv2 fragment (one byte at a time)
uint8_t * msv2_rx_data (MSV2_INST_t *msv2)
Getter for the pointer to the rx data array contained in the msv2 packet creator.
uint8_t * msv2_tx_data (MSV2_INST_t *msv2)
Getter for the pointer to the tx data array contained in the msv2 packet creator.
Macro Definition Documentation
DLE
#define DLE (0x90)
STX
#define STX (0x02)
Function Documentation
calc_field_CRC()
uint16_t calc_field_CRC (uint16_t * p_data_array, uint16_t length) [static]
Compute the CRC for a data packet.
Function taken from Maxon Serial V2 specification manual.
Parameters
p_data_array Pointer to the data array of the packet.
length Length of the packet
Note
The p_data_array data must contain two empty bytes [0x00, 0x00] at the end, where the CRC goes.
Referenced by msv2_create_frame(), and msv2_decode_fragment().
msv2_create_frame()
uint16_t msv2_create_frame (MSV2_INST_t * msv2, uint8_t opcode, uint8_t data_len, uint8_t * data)
Generate an msv2 packet.
Parameters
msv2 Pointer to the msv2 packet creator instance.
opcode Opcode to be placed in the packet header.
data_len Length of the packet data payload.
data Data to be placed in the packet payload.
References calc_field_CRC(), MSV2_TX_DATA::crc_data, MSV2_TX_DATA::data, MSV2_TX_DATA::data_len, DLE, MSV2_TX_DATA::opcode, STX, and MSV2_INST::tx.
msv2_decode_fragment()
MSV2_ERROR_t msv2_decode_fragment (MSV2_INST_t * msv2, uint8_t d)
Decode an msv2 fragment (one byte at a time)
Parameters
msv2 Pointer to the msv2 packet creator instance.
d Fragment to be decoded.
Note
This function is to be called upon reception of a byte.
References calc_field_CRC(), MSV2_RX_DATA::counter, MSV2_RX_DATA::crc, MSV2_RX_DATA::crc_data, MSV2_RX_DATA::data, MSV2_RX_DATA::data_len, DLE, MSV2_RX_DATA::escape, MSV2_RX_DATA::length, MSV2_PROGRESS, MSV2_SUCCESS, MSV2_WRONG_CRC, MSV2_RX_DATA::opcode, MSV2_INST::rx, MSV2_RX_DATA::state, STX, WAITING_CRC1, WAITING_CRC2, WAITING_DATA, WAITING_DLE, WAITING_LEN, WAITING_OPCODE, and WAITING_STX.
msv2_init()
void msv2_init (MSV2_INST_t * msv2)
Initialize a msv2 packet creator instance.
Parameters
msv2 Pointer to the msv2 instance to be initialized.
References MSV2_INST::id.
Referenced by debug_init().
msv2_rx_data()
uint8_t* msv2_rx_data (MSV2_INST_t * msv2)
Getter for the pointer to the rx data array contained in the msv2 packet creator.
Parameters
msv2 Pointer to the msv2 packet creator instance.
References MSV2_RX_DATA::data, and MSV2_INST::rx.
msv2_tx_data()
uint8_t* msv2_tx_data (MSV2_INST_t * msv2)
Getter for the pointer to the tx data array contained in the msv2 packet creator.
Parameters
msv2 Pointer to the msv2 packet creator instance.
References MSV2_TX_DATA::data, and MSV2_INST::tx.