serial.h File Reference
#include <stdint.h>
#include <device/device.h>
#include <util.h>
#include <semphr.h>
Data Structures
struct serial_deamon_context
struct serial_interface_context
Macros
#define SERIAL_BUFFER_LEN 256
Typedefs
typedef enum serial_interrupt_source serial_interrupt_source_t
typedef enum serial_transfer_mode serial_transfer_mode_t
typedef struct serial_deamon_context serial_deamon_context_t
typedef struct serial_interface_context serial_interface_context_t
Enumerations
enum serial_interrupt_source { SERIAL_SOURCE_DMA_FIRST_HALF
, SERIAL_SOURCE_DMA_SECOND_HALF
, SERIAL_SOURCE_IDLE
 }
enum serial_transfer_mode { SERIAL_TRANSFER_DMA
, SERIAL_TRANSFER_IT
 }
Functions
util_error_t serial_init (void)
util_error_t serial_feedback_init (void)
device_deamon_t * serial_get_deamon (void)
device_interface_t * serial_get_feedback_interface (void)
util_error_t serial_send (void *context, uint8_t *data, uint32_t len)
util_error_t serial_recv (void *context, uint8_t *data, uint32_t *len)
Macro Definition Documentation
SERIAL_BUFFER_LEN
#define SERIAL_BUFFER_LEN 256
Typedef Documentation
serial_deamon_context_t
typedef struct serial_deamon_context serial_deamon_context_t
serial_interface_context_t
typedef struct serial_interface_context serial_interface_context_t
serial_interrupt_source_t
typedef enum serial_interrupt_source serial_interrupt_source_t
serial_transfer_mode_t
typedef enum serial_transfer_mode serial_transfer_mode_t
Enumeration Type Documentation
serial_interrupt_source
enum serial_interrupt_source
Enumerator
SERIAL_SOURCE_DMA_FIRST_HALF
SERIAL_SOURCE_DMA_SECOND_HALF
SERIAL_SOURCE_IDLE
serial_transfer_mode
enum serial_transfer_mode
Enumerator
SERIAL_TRANSFER_DMA
SERIAL_TRANSFER_IT
Function Documentation
serial_feedback_init()
util_error_t serial_feedback_init (void)
References device_interface_create(), ER_SUCCESS, feedback_interface, feedback_interface_context, serial_deamon, serial_handle_data(), serial_recv(), serial_send(), serial_setup_reception(), and SERIAL_TRANSFER_IT.
serial_get_deamon()
device_deamon_t* serial_get_deamon (void)
References serial_deamon.
serial_get_feedback_interface()
device_interface_t* serial_get_feedback_interface (void)
References feedback_interface.
Referenced by debug_init().
serial_init()
util_error_t serial_init (void)
References device_deamon_create(), ER_SUCCESS, serial_deamon_context::rx_sem, serial_deamon_context::rx_sem_buffer, serial_data_ready(), and serial_deamon.
Referenced by threads_init().
serial_recv()
util_error_t serial_recv (void * context, uint8_t * data, uint32_t * len)
References ER_SUCCESS, serial_interface_context::rx_buffer, util_buffer_u8_get(), and util_buffer_u8_isempty().
Referenced by debug_init(), and serial_feedback_init().
serial_send()
util_error_t serial_send (void * context, uint8_t * data, uint32_t len)
References ER_SUCCESS, and serial_interface_context::uart.
Referenced by debug_init(), and serial_feedback_init().