serial.c File Reference
#include <util.h>
#include <usart.h>
#include <main.h>
#include `serial.h`
#include <device/device.h>
Macros
#define S1_UART huart2
#define S2_UART huart3
#define S3_UART huart6
#define SERIAL_DMA_LEN 32
Functions
util_error_t serial_data_ready (void *context)
util_error_t serial_send (void *context, uint8_t *data, uint32_t len)
util_error_t serial_recv (void *context, uint8_t *data, uint32_t *len)
util_error_t serial_handle_data (void *if_context, void *dem_context)
util_error_t serial_setup_reception (serial_interface_context_t *interface_context, serial_transfer_mode_t mode)
void HAL_UART_RxCpltCallback (UART_HandleTypeDef *huart)
device_deamon_t * serial_get_deamon (void)
device_interface_t * serial_get_feedback_interface (void)
util_error_t serial_init (void)
util_error_t serial_feedback_init (void)
Variables
static device_deamon_t serial_deamon
static device_interface_t feedback_interface
static serial_deamon_context_t serial_deamon_context
static serial_interface_context_t feedback_interface_context
Macro Definition Documentation
S1_UART
#define S1_UART huart2
S2_UART
#define S2_UART huart3
S3_UART
#define S3_UART huart6
SERIAL_DMA_LEN
#define SERIAL_DMA_LEN 32
Function Documentation
HAL_UART_RxCpltCallback()
void HAL_UART_RxCpltCallback (UART_HandleTypeDef * huart)
References device_interface::context, device_deamon::context, device_deamon::interfaces, device_deamon::interfaces_count, serial_interface_context::rx_buffer, serial_interface_context::rx_fragment, serial_deamon_context::rx_sem, serial_deamon, serial_interface_context::uart, and util_buffer_u8_add().
serial_data_ready()
util_error_t serial_data_ready (void * context)
References ER_SUCCESS, ER_TIMEOUT, and serial_deamon_context::rx_sem.
Referenced by serial_init().
serial_feedback_init()
util_error_t serial_feedback_init (void)
References device_interface_create(), ER_SUCCESS, feedback_interface, feedback_interface_context, serial_deamon, serial_handle_data(), serial_recv(), serial_send(), serial_setup_reception(), and SERIAL_TRANSFER_IT.
serial_get_deamon()
device_deamon_t* serial_get_deamon (void)
References serial_deamon.
serial_get_feedback_interface()
device_interface_t* serial_get_feedback_interface (void)
References feedback_interface.
Referenced by debug_init().
serial_handle_data()
util_error_t serial_handle_data (void * if_context, void * dem_context)
References ER_SUCCESS.
Referenced by serial_feedback_init().
serial_init()
util_error_t serial_init (void)
References device_deamon_create(), ER_SUCCESS, serial_deamon_context::rx_sem, serial_deamon_context::rx_sem_buffer, serial_data_ready(), and serial_deamon.
Referenced by threads_init().
serial_recv()
util_error_t serial_recv (void * context, uint8_t * data, uint32_t * len)
References ER_SUCCESS, serial_interface_context::rx_buffer, util_buffer_u8_get(), and util_buffer_u8_isempty().
Referenced by debug_init(), and serial_feedback_init().
serial_send()
util_error_t serial_send (void * context, uint8_t * data, uint32_t len)
References ER_SUCCESS, and serial_interface_context::uart.
Referenced by debug_init(), and serial_feedback_init().
serial_setup_reception()
util_error_t serial_setup_reception (serial_interface_context_t * interface_context, serial_transfer_mode_t mode)
References ER_FAILURE, ER_RESSOURCE_ERROR, serial_interface_context::rx_buffer, serial_interface_context::rx_data, serial_interface_context::rx_fragment, SERIAL_BUFFER_LEN, SERIAL_TRANSFER_DMA, SERIAL_TRANSFER_IT, serial_interface_context::uart, and util_buffer_u8_init().
Referenced by debug_init(), and serial_feedback_init().
Variable Documentation
feedback_interface
device_interface_t feedback_interface [static]
Referenced by debug_init(), serial_feedback_init(), and serial_get_feedback_interface().
feedback_interface_context
serial_interface_context_t feedback_interface_context [static]
Initial value:
= {
        .uart = &S3_UART
}
Referenced by serial_feedback_init().
serial_deamon
device_deamon_t serial_deamon [static]
Referenced by debug_init(), HAL_UART_RxCpltCallback(), serial_feedback_init(), serial_get_deamon(), and serial_init().
serial_deamon_context
serial_deamon_context_t serial_deamon_context [static]