threads.h File Reference
#include <stdint.h>
Functions
void threads_init (void)
Initialize all the threads of Wildhorn AV.
Function Documentation
threads_init()
void threads_init (void)
Initialize all the threads of Wildhorn AV.
This is the only function that needs to be called from the ST Auto-generated files. This is clever in case the autogeneration fails. This will minimize the code to be rewritten.
References buzzer_init(), control_handle, CONTROL_PRIO, CONTROL_SZ, control_thread(), CREATE_THREAD, ER_SUCCESS, hostproc_init(), i2c_init(), i2c_spi_guard(), led_feedback_init(), led_rgb_handle, LED_RGB_PRIO, LED_RGB_SZ, led_rgb_thread(), od_handle, od_init(), OD_PRIO, OD_SZ, od_update_task(), and serial_init().