threads.c File Reference
#include <cmsis_os.h>
#include <threads.h>
#include <wildhorn.h>
#include <feedback/led.h>
#include <feedback/buzzer.h>
#include <driver/serial.h>
#include <driver/i2c.h>
#include <control.h>
#include <device/hostproc.h>
#include <od/od.h>
Macros
#define DEFAULT_SZ (1024)
#define OD_SZ DEFAULT_SZ
#define OD_PRIO (6)
#define CONTROL_SZ DEFAULT_SZ
#define CONTROL_PRIO (6)
#define LED_RGB_SZ DEFAULT_SZ
#define LED_RGB_PRIO (0)
#define CREATE_THREAD(handle, name, func, cont, sz, prio)
macro to declare a static thread in FreeRTOS
Functions
void threads_init (void)
Initialize all the threads of Wildhorn AV.
Variables
static TaskHandle_t od_handle = NULL
static TaskHandle_t control_handle = NULL
static TaskHandle_t led_rgb_handle = NULL
Macro Definition Documentation
CONTROL_PRIO
#define CONTROL_PRIO (6)
CONTROL_SZ
#define CONTROL_SZ DEFAULT_SZ
CREATE_THREAD
#define CREATE_THREAD(handle, name, func, cont, sz, prio)
Value:
    static StaticTask_t name##_buffer; \
    static StackType_t name##_stack[ sz ]; \
    handle = xTaskCreateStatic(\
            func, \
            #name, \
            sz, \
            (void *) cont, \
            prio, \
            name##_stack, \
            &name##_buffer)
macro to declare a static thread in FreeRTOS
This macros make the necessary funtion calls to setup a stack and working area for the declaration of a static FreeRTOS thread.
Parameters
handle A TaskHandle_t object to reference the created Thread.
name A name for thread.
func The entry point for the thread.
cont The context for the thread.
sz The desired size for the thread stack.
prio The priority for the thread.
DEFAULT_SZ
#define DEFAULT_SZ (1024)
LED_RGB_PRIO
#define LED_RGB_PRIO (0)
LED_RGB_SZ
#define LED_RGB_SZ DEFAULT_SZ
OD_PRIO
#define OD_PRIO (6)
OD_SZ
#define OD_SZ DEFAULT_SZ
Function Documentation
threads_init()
void threads_init (void)
Initialize all the threads of Wildhorn AV.
This is the only function that needs to be called from the ST Auto-generated files. This is clever in case the autogeneration fails. This will minimize the code to be rewritten.
References buzzer_init(), control_handle, CONTROL_PRIO, CONTROL_SZ, control_thread(), CREATE_THREAD, ER_SUCCESS, hostproc_init(), i2c_init(), i2c_spi_guard(), led_feedback_init(), led_rgb_handle, LED_RGB_PRIO, LED_RGB_SZ, led_rgb_thread(), od_handle, od_init(), OD_PRIO, OD_SZ, od_update_task(), and serial_init().
Variable Documentation
control_handle
TaskHandle_t control_handle = NULL [static]
Referenced by threads_init().
led_rgb_handle
TaskHandle_t led_rgb_handle = NULL [static]
Referenced by threads_init().
od_handle
TaskHandle_t od_handle = NULL [static]
Referenced by threads_init().