util.h File Reference
#include <stdint.h>
#include <main.h>
#include <cmsis_os.h>
Data Structures
struct util_buffer_u8
struct util_buffer_u16
struct util_buffer_i16
Macros
#define WRITE_IN_REG(reg, mask, data) (reg) &= ~(mask); (reg) |= (data)
Macro to write masked data into a register.
#define ENTER_CRITICAL taskENTER_CRITICAL
Macro to enter a critical section.
#define EXIT_CRITICAL taskEXIT_CRITICAL
Macro to exit a critical section.
#define UTIL_GENERATE_BUFFER(type, name)
#define util_abs(a) ((a)<0?-(a):(a))
Typedefs
typedef enum util_error util_error_t
Unified error codes for the whole WildhornAV project.
typedef struct util_buffer_u8 util_buffer_u8_t
typedef struct util_buffer_u16 util_buffer_u16_t
typedef struct util_buffer_i16 util_buffer_i16_t
Enumerations
enum util_error {
ER_SUCCESS = 0
, ER_DATA_NOT_RDY = 0<<1
, ER_FAILURE = 1<<1
, ER_OUT_OF_RANGE = 1<<2
,
ER_TIMEOUT = 1<<3
, ER_RESSOURCE_ERROR = 1<<4
 }
Unified error codes for the whole WildhornAV project.
Functions
static void util_encode_u8 (uint8_t *data, uint8_t value)
static void util_encode_u16 (uint8_t *data, uint16_t value)
static void util_encode_u32 (uint8_t *data, uint32_t value)
static void util_encode_i8 (uint8_t *data, int8_t value)
static void util_encode_i16 (uint8_t *data, int16_t value)
static void util_encode_i32 (uint8_t *data, int32_t value)
static uint8_t util_decode_u8 (uint8_t *data)
static uint16_t util_decode_u16 (uint8_t *data)
static uint32_t util_decode_u32 (uint8_t *data)
static int8_t util_decode_i8 (uint8_t *data)
static int16_t util_decode_i16 (uint8_t *data)
static int32_t util_decode_i32 (uint8_t *data)
static void util_buffer_u8_init (util_buffer_u8_t *bfr, uint8_t *buffer, uint16_t bfr_len)
static void util_buffer_u8_add (util_buffer_u8_t *bfr, uint8_t d)
static uint8_t util_buffer_u8_get (util_buffer_u8_t *bfr)
static uint8_t util_buffer_u8_access (util_buffer_u8_t *bfr, int16_t ix)
static uint8_t util_buffer_u8_isempty (util_buffer_u8_t *bfr)
static void util_buffer_u16_init (util_buffer_u16_t *bfr, uint16_t *buffer, uint16_t bfr_len)
static void util_buffer_u16_add (util_buffer_u16_t *bfr, uint16_t d)
static uint16_t util_buffer_u16_get (util_buffer_u16_t *bfr)
static uint8_t util_buffer_u16_isempty (util_buffer_u16_t *bfr)
static void util_buffer_i16_init (util_buffer_i16_t *bfr, int16_t *buffer, uint16_t bfr_len)
static void util_buffer_i16_add (util_buffer_i16_t *bfr, int16_t d)
static int16_t util_buffer_i16_get (util_buffer_i16_t *bfr)
static uint8_t util_buffer_i16_isempty (util_buffer_i16_t *bfr)
Macro Definition Documentation
ENTER_CRITICAL
#define ENTER_CRITICAL taskENTER_CRITICAL
Macro to enter a critical section.
EXIT_CRITICAL
#define EXIT_CRITICAL taskEXIT_CRITICAL
Macro to exit a critical section.
util_abs
#define util_abs(a) ((a)<0?-(a):(a))
UTIL_GENERATE_BUFFER
#define UTIL_GENERATE_BUFFER(type, name)
Value:
    typedef struct UTIL_BUFFER_##name{ \
        uint16_t c_ix; \
        uint16_t l_ix; \
        uint16_t bfr_len; \
        type * buffer; \
    }UTIL_BUFFER_##name##_t; \
static inline void util_buffer_##name##_init(UTIL_BUFFER_##name##_t * bfr, type * buffer, uint16_t bfr_len) { \
    bfr->c_ix = 0; \
    bfr->l_ix = 0; \
    bfr->bfr_len = bfr_len; \
    bfr->buffer = buffer; \
} \
static inline void util_buffer_##name##_add(UTIL_BUFFER_##name##_t * bfr, type d) { \
    bfr->buffer[bfr->c_ix++] = d; \
    if(bfr->c_ix == bfr->bfr_len) bfr->c_ix = 0; \
} \
static inline type util_buffer_##name##_get(UTIL_BUFFER_##name##_t * bfr) { \
    type tmp = bfr->buffer[bfr->l_ix++]; \
    if(bfr->l_ix == bfr->bfr_len) bfr->l_ix=0; \
    return tmp; \
} \
static inline type util_buffer_##name##_access(UTIL_BUFFER_##name##_t * bfr, uint16_t ix) { \
    int16_t i = bfr->c_ix - ix - 1; \
    while(i < 0) i += bfr->bfr_len; \
    return bfr->buffer[i]; \
} \
static inline uint8_t util_buffer_##name##_isempty(UTIL_BUFFER_##name##_t * bfr) { \
    return bfr->l_ix == bfr->c_ix; \
}
WRITE_IN_REG
#define WRITE_IN_REG(reg, mask, data) (reg) &= ~(mask); (reg) |= (data)
Macro to write masked data into a register.
Typedef Documentation
util_buffer_i16_t
typedef struct util_buffer_i16 util_buffer_i16_t
util_buffer_u16_t
typedef struct util_buffer_u16 util_buffer_u16_t
util_buffer_u8_t
typedef struct util_buffer_u8 util_buffer_u8_t
util_error_t
typedef enum util_error util_error_t
Unified error codes for the whole WildhornAV project.
Note
The error codes can be ORed together to create more complex errors.
Enumeration Type Documentation
util_error
enum util_error
Unified error codes for the whole WildhornAV project.
Note
The error codes can be ORed together to create more complex errors.
Enumerator
ER_SUCCESS Operation completed successfully
ER_DATA_NOT_RDY Error due to lack of readiness
ER_FAILURE Error due to a generic failure
ER_OUT_OF_RANGE Error due to a range issue
ER_TIMEOUT Error due to a timeout
ER_RESSOURCE_ERROR Error due to a ressource issue
Function Documentation
util_buffer_i16_add()
static void util_buffer_i16_add (util_buffer_i16_t * bfr, int16_t d) [inline], [static]
References util_buffer_i16::bfr_len, util_buffer_i16::buffer, and util_buffer_i16::c_ix.
util_buffer_i16_get()
static int16_t util_buffer_i16_get (util_buffer_i16_t * bfr) [inline], [static]
References util_buffer_i16::bfr_len, util_buffer_i16::buffer, and util_buffer_i16::l_ix.
util_buffer_i16_init()
static void util_buffer_i16_init (util_buffer_i16_t * bfr, int16_t * buffer, uint16_t bfr_len) [inline], [static]
References util_buffer_i16::bfr_len, util_buffer_i16::buffer, util_buffer_i16::c_ix, and util_buffer_i16::l_ix.
util_buffer_i16_isempty()
static uint8_t util_buffer_i16_isempty (util_buffer_i16_t * bfr) [inline], [static]
References util_buffer_i16::c_ix, and util_buffer_i16::l_ix.
util_buffer_u16_add()
static void util_buffer_u16_add (util_buffer_u16_t * bfr, uint16_t d) [inline], [static]
References util_buffer_u16::bfr_len, util_buffer_u16::buffer, and util_buffer_u16::c_ix.
util_buffer_u16_get()
static uint16_t util_buffer_u16_get (util_buffer_u16_t * bfr) [inline], [static]
References util_buffer_u16::bfr_len, util_buffer_u16::buffer, and util_buffer_u16::l_ix.
util_buffer_u16_init()
static void util_buffer_u16_init (util_buffer_u16_t * bfr, uint16_t * buffer, uint16_t bfr_len) [inline], [static]
References util_buffer_u16::bfr_len, util_buffer_u16::buffer, util_buffer_u16::c_ix, and util_buffer_u16::l_ix.
util_buffer_u16_isempty()
static uint8_t util_buffer_u16_isempty (util_buffer_u16_t * bfr) [inline], [static]
References util_buffer_u16::c_ix, and util_buffer_u16::l_ix.
util_buffer_u8_access()
static uint8_t util_buffer_u8_access (util_buffer_u8_t * bfr, int16_t ix) [inline], [static]
References util_buffer_u8::bfr_len, util_buffer_u8::buffer, and util_buffer_u8::c_ix.
util_buffer_u8_add()
static void util_buffer_u8_add (util_buffer_u8_t * bfr, uint8_t d) [inline], [static]
References util_buffer_u8::bfr_len, util_buffer_u8::buffer, and util_buffer_u8::c_ix.
Referenced by HAL_UART_RxCpltCallback().
util_buffer_u8_get()
static uint8_t util_buffer_u8_get (util_buffer_u8_t * bfr) [inline], [static]
References util_buffer_u8::bfr_len, util_buffer_u8::buffer, and util_buffer_u8::l_ix.
Referenced by serial_recv().
util_buffer_u8_init()
static void util_buffer_u8_init (util_buffer_u8_t * bfr, uint8_t * buffer, uint16_t bfr_len) [inline], [static]
References util_buffer_u8::bfr_len, util_buffer_u8::buffer, util_buffer_u8::c_ix, and util_buffer_u8::l_ix.
Referenced by serial_setup_reception().
util_buffer_u8_isempty()
static uint8_t util_buffer_u8_isempty (util_buffer_u8_t * bfr) [inline], [static]
References util_buffer_u8::c_ix, and util_buffer_u8::l_ix.
Referenced by serial_recv().
util_decode_i16()
static int16_t util_decode_i16 (uint8_t * data) [inline], [static]
Referenced by device_read_i16().
util_decode_i32()
static int32_t util_decode_i32 (uint8_t * data) [inline], [static]
Referenced by device_read_i32().
util_decode_i8()
static int8_t util_decode_i8 (uint8_t * data) [inline], [static]
Referenced by device_read_i8().
util_decode_u16()
static uint16_t util_decode_u16 (uint8_t * data) [inline], [static]
Referenced by device_read_u16().
util_decode_u32()
static uint32_t util_decode_u32 (uint8_t * data) [inline], [static]
Referenced by device_read_u32().
util_decode_u8()
static uint8_t util_decode_u8 (uint8_t * data) [inline], [static]
Referenced by device_read_u8().
util_encode_i16()
static void util_encode_i16 (uint8_t * data, int16_t value) [inline], [static]
Referenced by device_write_i16().
util_encode_i32()
static void util_encode_i32 (uint8_t * data, int32_t value) [inline], [static]
Referenced by device_write_i32().
util_encode_i8()
static void util_encode_i8 (uint8_t * data, int8_t value) [inline], [static]
Referenced by device_write_i8().
util_encode_u16()
static void util_encode_u16 (uint8_t * data, uint16_t value) [inline], [static]
Referenced by device_write_u16().
util_encode_u32()
static void util_encode_u32 (uint8_t * data, uint32_t value) [inline], [static]
Referenced by device_write_u32().
util_encode_u8()
static void util_encode_u8 (uint8_t * data, uint8_t value) [inline], [static]
Referenced by device_write_u8().